CREATE DATABASE OrdersDb;
GO

USE OrdersDb;

CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Customer NVARCHAR(100) NOT NULL,
    Product NVARCHAR(100) NOT NULL,
    Qty INT NOT NULL,
    Price DECIMAL(18,2) NOT NULL
);